/**
 * Embeds the OG-card fonts as base64 so image rendering needs no filesystem
 * access (Cloudflare Workers has none) and no network fetches.
 *
 *   pnpm tsx scripts/generate-og-fonts.ts
 *
 * Reads Latin .woff subsets from node_modules/@fontsource/* (satori reads
 * ttf/otf/woff, not woff2) and writes app/.server/og/fonts.generated.ts.
 * Re-run after bumping a @fontsource package or changing FONTS below.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const FONTS = [
  { name: "Bricolage Grotesque", weight: 700, file: "@fontsource/bricolage-grotesque/files/bricolage-grotesque-latin-700-normal.woff" },
  { name: "Bricolage Grotesque", weight: 800, file: "@fontsource/bricolage-grotesque/files/bricolage-grotesque-latin-800-normal.woff" },
  { name: "Instrument Sans", weight: 500, file: "@fontsource/instrument-sans/files/instrument-sans-latin-500-normal.woff" },
  { name: "Instrument Sans", weight: 700, file: "@fontsource/instrument-sans/files/instrument-sans-latin-700-normal.woff" },
] as const;

const require = createRequire(import.meta.url);
const out = fileURLToPath(new URL("../app/.server/og/fonts.generated.ts", import.meta.url));

let total = 0;
const entries = FONTS.map((font) => {
  const bytes = readFileSync(require.resolve(font.file));
  total += bytes.byteLength;
  const version = (require(`${font.file.split("/files/")[0]}/package.json`) as { version: string }).version;
  return [
    "  {",
    `    name: ${JSON.stringify(font.name)},`,
    `    weight: ${font.weight},`,
    `    source: ${JSON.stringify(`${font.file} (v${version}, ${bytes.byteLength} bytes)`)},`,
    `    base64: ${JSON.stringify(bytes.toString("base64"))},`,
    "  },",
  ].join("\n");
});

writeFileSync(
  out,
  [
    "// AUTO-GENERATED by scripts/generate-og-fonts.ts. Do not edit by hand.",
    "// Fonts: SIL Open Font License 1.1 (Bricolage Grotesque, Instrument Sans), via @fontsource.",
    "",
    "export interface EmbeddedFont {",
    "  readonly name: string;",
    "  readonly weight: 400 | 500 | 600 | 700 | 800;",
    "  readonly source: string;",
    "  readonly base64: string;",
    "}",
    "",
    "export const EMBEDDED_FONTS: ReadonlyArray<EmbeddedFont> = [",
    ...entries,
    "];",
    "",
  ].join("\n"),
);

console.log(`Wrote ${out} (${FONTS.length} fonts, ${(total / 1024).toFixed(1)} KiB raw)`);
